import { Metadata } from "next";

import { Footer } from "../../../components/footer";
import { Header } from "../../../components/header";
import { ErrorWrapper } from "./error-wrapper";

import "./global.css";

export const metadata: Metadata = {
  title: {
    default: "Next.js tutorial - Codevolution",
    template: "%s | Codevolution",
  },
  description: "Generated by Next.js",
};

export default function MarketingLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />

        <main>
          <ErrorWrapper>{children}</ErrorWrapper>
        </main>

        <Footer />
      </body>
    </html>
  );
}
